In [1]:
import numpy as np

In [8]:
Arr = np.random.randint(0,10,size=[12,12])

In [26]:
print(Arr)

[[6 7 3 3 8 1 2 5 4 3 8 9]
 [3 2 8 7 7 6 1 6 2 6 8 1]
 [3 7 3 4 0 1 2 4 6 1 7 2]
 [2 1 3 9 1 2 1 7 1 8 6 8]
 [5 0 6 2 3 2 5 8 6 2 0 6]
 [5 4 0 8 4 5 5 3 5 5 0 2]
 [5 6 3 2 0 0 1 1 0 6 1 7]
 [5 6 7 5 3 6 8 8 7 9 9 3]
 [9 3 8 9 7 0 1 9 8 4 6 3]
 [4 7 1 3 3 1 4 2 8 2 5 1]
 [8 4 3 9 2 7 8 5 8 1 2 5]
 [1 2 5 9 2 6 7 4 5 6 3 1]]


In [27]:
ps = 2
N = int(12/ps)
Ans=[]
for i in range(N):
  An=[]
  for j in range(N):
    Arr1 = Arr[i*ps:i*ps+ps,j*ps:j*ps+ps]
    An.append(np.max(Arr1))
  Ans.append(An)

np.around(Ans, 2) 

array([[7, 8, 8, 6, 6, 9],
       [7, 9, 2, 7, 8, 8],
       [5, 8, 5, 8, 6, 6],
       [6, 7, 6, 8, 9, 9],
       [9, 9, 7, 9, 8, 6],
       [8, 9, 7, 8, 8, 5]])

In [28]:
ps = 3
N = int(12/ps)
Ans=[]
for i in range(N):
  An=[]
  for j in range(N):
    Arr1 = Arr[i*ps:i*ps+ps,j*ps:j*ps+ps]
    An.append(np.max(Arr1))
  Ans.append(An)

np.around(Ans, 2) 

array([[8, 8, 6, 9],
       [6, 9, 8, 8],
       [9, 9, 9, 9],
       [8, 9, 8, 6]])